# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: On Blahfe
email: nab at blahfe.com
description: > # this means to ignore newlines until "baseurl:"
  MFA at Kanazawa College of Art. Founded Blahfe, a protective force
  focusing on pain points. Utagaki developer. Love coffee, love art.
author: "なびの:construction_worker:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nabinno.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: nabinno
utagaki_username: nabinno

# Build settings
theme: minima
permalink: pretty
highlighter: pygments
markdown: kramdown
permalink: date
use_tex: false
use_divs: true
gems:
  - jekyll-feed
  - jekyll-plantuml
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  - jemoji
  - jekyll-relative-links
  - jekyll-avatar
exclude:
  - Gemfile
  - Gemfile.lock
jekyll-mentions: https://twitter.com
