version: 2.1

jobs:
  build_deploy:
    docker:
      - image: circleci/node:12.4
    steps:
      - checkout
      - run:
          name: Install NPM
          command: npm install
      - run:
          name: Build
          command: npm run clean && npm run build
      - add_ssh_keys:
          fingerprints:
            - "a3:d2:4d:04:e8:cb:16:16:91:b4:2c:d7:9a:c7:c4:de"
      - deploy:
          name: Deploy
          command: |
            git config --global user.email "nab+circleci@blahfe.com"
            git config --global user.name "nabinno+circleci"
            git add .
            git commit -m "[skip ci]Run npm run clean && npm run build."
            git push origin master

workflows:
  build_deploy:
    jobs:
      - build_deploy:
          filters:
            branches:
              only: master
